[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
bevy_spacetimedb = "0.6.0"
clap = { version = "4.5.40", features = ["derive"] }
spacetimedb-sdk = "1.2.0"
reqwest = { version = "0.12.22", features = ["json"] }
tokio = "1.46.1"
serde = "1.0.219"
