version: "3.8"

services:
  server:
    build:
      context: game/server
    container_name: spacetime-character-game-server
    ports:
      - "3000:3000"  # Expose to host
    networks:
      - spacetime-net

  client1:
    build:
      context: game/client
    container_name: spacetime-client1
    depends_on:
      - server
    networks:
      - spacetime-net

  client2:
    build:
      context: game/client
    container_name: spacetime-client2
    depends_on:
      - server
    networks:
      - spacetime-net

networks:
  spacetime-net:
