// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using character cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::identity_binding_type::IdentityBinding;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `identity_bindings`.
///
/// Obtain a handle from the [`IdentityBindingsTableAccess::identity_bindings`] method on [`super::RemoteTables`],
/// like `ctx.db.identity_bindings()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.identity_bindings().on_insert(...)`.
pub struct IdentityBindingsTableHandle<'ctx> {
    imp: __sdk::TableHandle<IdentityBinding>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `identity_bindings`.
///
/// Implemented for [`super::RemoteTables`].
pub trait IdentityBindingsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`IdentityBindingsTableHandle`], which mediates access to the table `identity_bindings`.
    fn identity_bindings(&self) -> IdentityBindingsTableHandle<'_>;
}

impl IdentityBindingsTableAccess for super::RemoteTables {
    fn identity_bindings(&self) -> IdentityBindingsTableHandle<'_> {
        IdentityBindingsTableHandle {
            imp: self.imp.get_table::<IdentityBinding>("identity_bindings"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct IdentityBindingsInsertCallbackId(__sdk::CallbackId);
pub struct IdentityBindingsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for IdentityBindingsTableHandle<'ctx> {
    type Row = IdentityBinding;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = IdentityBinding> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = IdentityBindingsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IdentityBindingsInsertCallbackId {
        IdentityBindingsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: IdentityBindingsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = IdentityBindingsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> IdentityBindingsDeleteCallbackId {
        IdentityBindingsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: IdentityBindingsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(crate) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<IdentityBinding>("identity_bindings");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub struct IdentityBindingsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for IdentityBindingsTableHandle<'ctx> {
    type UpdateCallbackId = IdentityBindingsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> IdentityBindingsUpdateCallbackId {
        IdentityBindingsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: IdentityBindingsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(crate) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<IdentityBinding>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<IdentityBinding>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `identity` unique index on the table `identity_bindings`,
/// which allows point queries on the field of the same name
/// via the [`IdentityBindingsIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.identity_bindings().identity().find(...)`.
pub struct IdentityBindingsIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<IdentityBinding, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> IdentityBindingsTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `identity_bindings`.
    pub fn identity(&self) -> IdentityBindingsIdentityUnique<'ctx> {
        IdentityBindingsIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> IdentityBindingsIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<IdentityBinding> {
        self.imp.find(col_val)
    }
}
