[server]
module = "my-game"
address = "0.0.0.0"
port = 3000

[jwt]
issuer = "http://localhost:3010"
audience = "spacetimedb"


[auth]
jwt_algorithm = "RS256"
jwt_jwks_url = "http://localhost:3010/.well-known/jwks.json"



[logging]
level = "debug"
