// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::character_movement_state_type::CharacterMovementState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `character_movement`.
///
/// Obtain a handle from the [`CharacterMovementTableAccess::character_movement`] method on [`super::RemoteTables`],
/// like `ctx.db.character_movement()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_movement().on_insert(...)`.
pub struct CharacterMovementTableHandle<'ctx> {
    imp: __sdk::TableHandle<CharacterMovementState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `character_movement`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CharacterMovementTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CharacterMovementTableHandle`], which mediates access to the table `character_movement`.
    fn character_movement(&self) -> CharacterMovementTableHandle<'_>;
}

impl CharacterMovementTableAccess for super::RemoteTables {
    fn character_movement(&self) -> CharacterMovementTableHandle<'_> {
        CharacterMovementTableHandle {
            imp: self
                .imp
                .get_table::<CharacterMovementState>("character_movement"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CharacterMovementInsertCallbackId(__sdk::CallbackId);
pub struct CharacterMovementDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CharacterMovementTableHandle<'ctx> {
    type Row = CharacterMovementState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CharacterMovementState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CharacterMovementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterMovementInsertCallbackId {
        CharacterMovementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CharacterMovementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CharacterMovementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CharacterMovementDeleteCallbackId {
        CharacterMovementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CharacterMovementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CharacterMovementState>("character_movement");
    _table.add_unique_constraint::<u128>("id", |row| &row.id);
}
pub struct CharacterMovementUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CharacterMovementTableHandle<'ctx> {
    type UpdateCallbackId = CharacterMovementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CharacterMovementUpdateCallbackId {
        CharacterMovementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CharacterMovementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CharacterMovementState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CharacterMovementState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `character_movement`,
/// which allows point queries on the field of the same name
/// via the [`CharacterMovementIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.character_movement().id().find(...)`.
pub struct CharacterMovementIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CharacterMovementState, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CharacterMovementTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `character_movement`.
    pub fn id(&self) -> CharacterMovementIdUnique<'ctx> {
        CharacterMovementIdUnique {
            imp: self.imp.get_unique_constraint::<u128>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CharacterMovementIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<CharacterMovementState> {
        self.imp.find(col_val)
    }
}
