// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::player_movement_state_type::PlayerMovementState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_movement`.
///
/// Obtain a handle from the [`PlayerMovementTableAccess::player_movement`] method on [`super::RemoteTables`],
/// like `ctx.db.player_movement()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_movement().on_insert(...)`.
pub struct PlayerMovementTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerMovementState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_movement`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerMovementTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerMovementTableHandle`], which mediates access to the table `player_movement`.
    fn player_movement(&self) -> PlayerMovementTableHandle<'_>;
}

impl PlayerMovementTableAccess for super::RemoteTables {
    fn player_movement(&self) -> PlayerMovementTableHandle<'_> {
        PlayerMovementTableHandle {
            imp: self.imp.get_table::<PlayerMovementState>("player_movement"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerMovementInsertCallbackId(__sdk::CallbackId);
pub struct PlayerMovementDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerMovementTableHandle<'ctx> {
    type Row = PlayerMovementState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerMovementState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerMovementInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerMovementInsertCallbackId {
        PlayerMovementInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerMovementInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerMovementDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerMovementDeleteCallbackId {
        PlayerMovementDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerMovementDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerMovementState>("player_movement");
    _table.add_unique_constraint::<__sdk::Identity>("player_id", |row| &row.player_id);
}
pub struct PlayerMovementUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerMovementTableHandle<'ctx> {
    type UpdateCallbackId = PlayerMovementUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerMovementUpdateCallbackId {
        PlayerMovementUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerMovementUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerMovementState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerMovementState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `player_id` unique index on the table `player_movement`,
/// which allows point queries on the field of the same name
/// via the [`PlayerMovementPlayerIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_movement().player_id().find(...)`.
pub struct PlayerMovementPlayerIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerMovementState, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerMovementTableHandle<'ctx> {
    /// Get a handle on the `player_id` unique index on the table `player_movement`.
    pub fn player_id(&self) -> PlayerMovementPlayerIdUnique<'ctx> {
        PlayerMovementPlayerIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("player_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerMovementPlayerIdUnique<'ctx> {
    /// Find the subscribed row whose `player_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<PlayerMovementState> {
        self.imp.find(col_val)
    }
}
