// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using stdb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(crate) struct SelectCharacterArgs {
    pub character_id: u128,
}

impl From<SelectCharacterArgs> for super::Reducer {
    fn from(args: SelectCharacterArgs) -> Self {
        Self::SelectCharacter {
            character_id: args.character_id,
        }
    }
}

impl __sdk::InModule for SelectCharacterArgs {
    type Module = super::RemoteModule;
}

pub struct SelectCharacterCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `select_character`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait select_character {
    /// Request that the remote module invoke the reducer `select_character` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_select_character`] callbacks.
    fn select_character(&self, character_id: u128) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `select_character`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SelectCharacterCallbackId`] can be passed to [`Self::remove_on_select_character`]
    /// to cancel the callback.
    fn on_select_character(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u128) + Send + 'static,
    ) -> SelectCharacterCallbackId;
    /// Cancel a callback previously registered by [`Self::on_select_character`],
    /// causing it not to run in the future.
    fn remove_on_select_character(&self, callback: SelectCharacterCallbackId);
}

impl select_character for super::RemoteReducers {
    fn select_character(&self, character_id: u128) -> __sdk::Result<()> {
        self.imp
            .call_reducer("select_character", SelectCharacterArgs { character_id })
    }
    fn on_select_character(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u128) + Send + 'static,
    ) -> SelectCharacterCallbackId {
        SelectCharacterCallbackId(self.imp.on_reducer(
            "select_character",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SelectCharacter { character_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, character_id)
            }),
        ))
    }
    fn remove_on_select_character(&self, callback: SelectCharacterCallbackId) {
        self.imp.remove_on_reducer("select_character", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `select_character`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_select_character {
    /// Set the call-reducer flags for the reducer `select_character` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn select_character(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_select_character for super::SetReducerFlags {
    fn select_character(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("select_character", flags);
    }
}
