// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using stdb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::user_account_type::UserAccount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `user_accounts`.
///
/// Obtain a handle from the [`UserAccountsTableAccess::user_accounts`] method on [`super::RemoteTables`],
/// like `ctx.db.user_accounts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_accounts().on_insert(...)`.
pub struct UserAccountsTableHandle<'ctx> {
    imp: __sdk::TableHandle<UserAccount>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `user_accounts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait UserAccountsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`UserAccountsTableHandle`], which mediates access to the table `user_accounts`.
    fn user_accounts(&self) -> UserAccountsTableHandle<'_>;
}

impl UserAccountsTableAccess for super::RemoteTables {
    fn user_accounts(&self) -> UserAccountsTableHandle<'_> {
        UserAccountsTableHandle {
            imp: self.imp.get_table::<UserAccount>("user_accounts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct UserAccountsInsertCallbackId(__sdk::CallbackId);
pub struct UserAccountsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for UserAccountsTableHandle<'ctx> {
    type Row = UserAccount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = UserAccount> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = UserAccountsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserAccountsInsertCallbackId {
        UserAccountsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: UserAccountsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = UserAccountsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> UserAccountsDeleteCallbackId {
        UserAccountsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: UserAccountsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(crate) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<UserAccount>("user_accounts");
    _table.add_unique_constraint::<u128>("id", |row| &row.id);
    _table.add_unique_constraint::<String>("email", |row| &row.email);
}
pub struct UserAccountsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for UserAccountsTableHandle<'ctx> {
    type UpdateCallbackId = UserAccountsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> UserAccountsUpdateCallbackId {
        UserAccountsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: UserAccountsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(crate) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<UserAccount>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<UserAccount>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `user_accounts`,
/// which allows point queries on the field of the same name
/// via the [`UserAccountsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_accounts().id().find(...)`.
pub struct UserAccountsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserAccount, u128>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserAccountsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `user_accounts`.
    pub fn id(&self) -> UserAccountsIdUnique<'ctx> {
        UserAccountsIdUnique {
            imp: self.imp.get_unique_constraint::<u128>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserAccountsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u128) -> Option<UserAccount> {
        self.imp.find(col_val)
    }
}

/// Access to the `email` unique index on the table `user_accounts`,
/// which allows point queries on the field of the same name
/// via the [`UserAccountsEmailUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.user_accounts().email().find(...)`.
pub struct UserAccountsEmailUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<UserAccount, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> UserAccountsTableHandle<'ctx> {
    /// Get a handle on the `email` unique index on the table `user_accounts`.
    pub fn email(&self) -> UserAccountsEmailUnique<'ctx> {
        UserAccountsEmailUnique {
            imp: self.imp.get_unique_constraint::<String>("email"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> UserAccountsEmailUnique<'ctx> {
    /// Find the subscribed row whose `email` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<UserAccount> {
        self.imp.find(col_val)
    }
}
